on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: CI

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install --frozen-lockfile
      - run: yarn run mirror-box
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run lint
        env:
          CI: true

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run type-check
        env:
          CI: true

  test:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn run test
        env:
          CI: true
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/cache@v1
        id: restore-deps
        with:
          path: "."
          key: ${{ github.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: yarn dev
          wait-on: 'http://localhost:3000'
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
